version: '3.7'
services:
  influxdb:
    image: "influxdb"
    hostname: "influxdb"
    ports:
      - "8086:8086"
    networks:
      - iot-labs
    labels:
       NAME: "influxdb"
  
  influxdbchrono:
    image: "chronograf"
    hostname: "chronograf"
    ports:
    - "8087:8888"
    networks:
    - iot-labs
    labels:
       NAME: "chronograf"
    command: "--influxdb-url=http://influxdb:8086"

  grafana:
   image: "grafana/grafana"
   hostname: "grafana"
   environment:
    GF_SECURITY_ADMIN_PASSWORD: "secret"
   ports:
     - "8084:3000"
   networks:
     - iot-labs
   labels:
     NAME: "grafana"
networks:
  iot-labs:
      external: true
