version: '3.7'
services:
  nifi:
    image: "apache/nifi:1.9.2"
    hostname: "nifi"
    environment:
      NIFI_WEB_HTTP_PORT: "8080"
    ports:
      - "8083:8080"
    volumes:
    - "input/.input"
    - "output/.output"
    networks:
      - iot-labs
    labels:
       NAME: "nifi"
networks:
  iot-labs:
      external: true
